application: pocket

version: 1
runtime: go
api_version: go1

handlers:
- url: /(favicon\.ico)$
  static_files: static/\1
  upload: static/favicon.ico

- url: /(humans\.txt)$
  static_files: static/\1
  upload: static/humans.txt
